### ISSUE TITLE
Nieprawidłowy status na kilka minut

### ISSUE THREAD

**Issue by Jordan87** [PePeLLee/home-assistant-pse-calendar#1]
Cześć

Dziś zauważyłem że po godzinie 12 na ponad trzy minuty zmienił sie status encji "PSE Uzywanie" niezgodnie z tym co widać na stronie PSE, no chyba ze akurat na chwile zmienili to. :)

![image](https://github.com/PePeLLee/home-assistant-pse-calendar/assets/10414918/f29e66f8-2d7a-4ea0-b201-ce7423863b08)

Jak tutaj zgrać jakieś przydatne logi?

**Comment by PePeLLee** [comment]
Sprawdziłem u siebie, nic nie było:
![image](https://github.com/PePeLLee/home-assistant-pse-calendar/assets/61408245/e41a2140-838c-451c-80cb-f92c1d86ca5b)

Niestety nie przewidziałem żadnego logowania danych wejściowych. Szczerze mówiąc nie bardzo mam pomysł jak by to mogło wyglądać.

Integracja pobiera dane z sieci co 30 min i aktualizuje kalendarz. Logowanie musiało by polegać na zapisywaniu całego csv do logów a to było by mocno duże.

Jeżeli sytuacja się powtórzy coś pomyślę.

**Comment by Jordan87** [comment]
Dzis tez jakies dziwne anomalnie do "używania"
![image](https://github.com/PePeLLee/home-assistant-pse-calendar/assets/10414918/4e56618b-287f-45f3-b047-a4e873897d39)
![image](https://github.com/PePeLLee/home-assistant-pse-calendar/assets/10414918/edf1fd6b-be30-4d97-8595-6b1f8a2ba90b)

**Comment by PePeLLee** [comment]
Rano sprawdzałem na stronie i widzę że zmienili csv w ciągu dnia. Nic na to nie poradzimy

**Comment by Jordan87** [comment]
Ok, jesli to oni zmieniaja to w porzadku, nie ma co kombinowac.
U ciebie dzis tez tak pokazal czy moze jest tak ze dodatek moze w roznych godzinach pobierac dane?

**Comment by PePeLLee** [comment]
Stan kalendarza aktualizuje się co kilka sekund ale dane z sieci pobierane są co pół godziny ale nie o np. pełnej godzinie, więc u mnie może być inaczej. Wczoraj tak to wyglądało:
![image](https://github.com/PePeLLee/home-assistant-pse-calendar/assets/61408245/0f28bc4b-dcb5-4bd9-a488-a3e3e387e450)

Zmieniało się w połowie godziny a tego nie da się odzwierciedlić w pliku CSV na stronie więc musiało się zmieniać pomiędzy pobraniami
