### ISSUE TITLE
Nie można pobrać przez HACS

### ISSUE THREAD

**Issue by DoubleWhisky** [PePeLLee/home-assistant-pse-calendar#2]
Download failed - Got status code 404 when trying to download https://github.com/PePeLLee/home-assistant-pse-calendar/releases/download/main/pse.zip
Download failed - Got status code 404 when trying to download https://github.com/PePeLLee/home-assistant-pse-calendar/releases/download/1.0/pse.zip

**Comment by PePeLLee** [comment]
Zobacz teraz, powinno być ok.

**Comment by DoubleWhisky** [comment]
Potwierdzam. Jest OK. Dzięki!
